blocks:
  default: >-
    []
  json_schema: >-
    {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "campaign_id": {
            "type": "string",
            "description": "Campaign ID for this block"
          },
          "params": {
            "type": "array",
            "format": "table",
            "uniqueItems": true,
            "items": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                },
                "value": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    }
show_in_routes:
  type: list
  list_type: "simple"
  default: ""
  description: "Advanced users only: limit sidebar to the selected routes. <br/><br/>Examples: discovery.latest, discovery.unread, discovery.new, discovery.top, tag.show, \"c/category-slug\" (for categories), \"tag/sample-tag\" (for tags). <br/><br/>When empty, the sidebar is shown on all list routes."
  allow_any: true
  choices:
  api_endpoint:
  default: "https://api.example.com/endpoint"
  client: true
  placement_id:
  default: "right-side-blocks"
  client: true
  description: "Placement ID is required for analytics"
